// AUTO-GENERATED by scripts/gen-cli-commands.mjs — do not edit by hand.
// Describes every namespace method so the CLI can dispatch and self-document.

export type CliParamRole = "positional" | "body" | "query";

export interface CliParam {
  name: string;
  role: CliParamRole;
}

export interface CliCommand {
  namespace: string;
  command: string;
  method: string;
  verb: string;
  path: string;
  pathParams: string[];
  params: CliParam[];
  hasBody: boolean;
  hasQuery: boolean;
  nonEnvelope: boolean;
}

export const COMMANDS: readonly CliCommand[] = [
  {
    "namespace": "agentIntegrations",
    "command": "authorize-composio",
    "method": "authorizeComposio",
    "verb": "POST",
    "path": "/agent-integrations/composio/authorize",
    "pathParams": [],
    "params": [
      {
        "name": "body",
        "role": "body"
      }
    ],
    "hasBody": true,
    "hasQuery": false,
    "nonEnvelope": false
  },
  {
    "namespace": "agentIntegrations",
    "command": "claim-history-reward",
    "method": "claimHistoryReward",
    "verb": "POST",
    "path": "/agent-integrations/history-rewards/claim",
    "pathParams": [],
    "params": [],
    "hasBody": false,
    "hasQuery": false,
    "nonEnvelope": false
  },
  {
    "namespace": "agentIntegrations",
    "command": "connect-recall-calendar",
    "method": "connectRecallCalendar",
    "verb": "POST",
    "path": "/agent-integrations/recall-calendar/connect",
    "pathParams": [],
    "params": [],
    "hasBody": false,
    "hasQuery": false,
    "nonEnvelope": false
  },
  {
    "namespace": "agentIntegrations",
    "command": "create-composio-trigger",
    "method": "createComposioTrigger",
    "verb": "POST",
    "path": "/agent-integrations/composio/triggers",
    "pathParams": [],
    "params": [
      {
        "name": "body",
        "role": "body"
      }
    ],
    "hasBody": true,
    "hasQuery": false,
    "nonEnvelope": false
  },
  {
    "namespace": "agentIntegrations",
    "command": "crypto-bridge",
    "method": "cryptoBridge",
    "verb": "POST",
    "path": "/agent-integrations/crypto/bridge",
    "pathParams": [],
    "params": [
      {
        "name": "body",
        "role": "body"
      }
    ],
    "hasBody": true,
    "hasQuery": false,
    "nonEnvelope": false
  },
  {
    "namespace": "agentIntegrations",
    "command": "crypto-swap",
    "method": "cryptoSwap",
    "verb": "POST",
    "path": "/agent-integrations/crypto/swap",
    "pathParams": [],
    "params": [
      {
        "name": "body",
        "role": "body"
      }
    ],
    "hasBody": true,
    "hasQuery": false,
    "nonEnvelope": false
  },
  {
    "namespace": "agentIntegrations",
    "command": "delete-composio-connection",
    "method": "deleteComposioConnection",
    "verb": "DELETE",
    "path": "/agent-integrations/composio/connections/:connectionId",
    "pathParams": [
      "connectionId"
    ],
    "params": [
      {
        "name": "connectionId",
        "role": "positional"
      }
    ],
    "hasBody": false,
    "hasQuery": false,
    "nonEnvelope": false
  },
  {
    "namespace": "agentIntegrations",
    "command": "delete-composio-trigger",
    "method": "deleteComposioTrigger",
    "verb": "DELETE",
    "path": "/agent-integrations/composio/triggers/:triggerId",
    "pathParams": [
      "triggerId"
    ],
    "params": [
      {
        "name": "triggerId",
        "role": "positional"
      }
    ],
    "hasBody": false,
    "hasQuery": false,
    "nonEnvelope": false
  },
  {
    "namespace": "agentIntegrations",
    "command": "delete-file",
    "method": "deleteFile",
    "verb": "DELETE",
    "path": "/agent-integrations/file-storage/files/:fileId",
    "pathParams": [
      "fileId"
    ],
    "params": [
      {
        "name": "fileId",
        "role": "positional"
      }
    ],
    "hasBody": false,
    "hasQuery": false,
    "nonEnvelope": false
  },
  {
    "namespace": "agentIntegrations",
    "command": "disconnect-recall-calendar",
    "method": "disconnectRecallCalendar",
    "verb": "POST",
    "path": "/agent-integrations/recall-calendar/disconnect",
    "pathParams": [],
    "params": [],
    "hasBody": false,
    "hasQuery": false,
    "nonEnvelope": false
  },
  {
    "namespace": "agentIntegrations",
    "command": "download-file",
    "method": "downloadFile",
    "verb": "GET",
    "path": "/agent-integrations/file-storage/files/:fileId/download",
    "pathParams": [
      "fileId"
    ],
    "params": [
      {
        "name": "fileId",
        "role": "positional"
      }
    ],
    "hasBody": false,
    "hasQuery": false,
    "nonEnvelope": false
  },
  {
    "namespace": "agentIntegrations",
    "command": "execute-composio-tool",
    "method": "executeComposioTool",
    "verb": "POST",
    "path": "/agent-integrations/composio/execute",
    "pathParams": [],
    "params": [
      {
        "name": "body",
        "role": "body"
      }
    ],
    "hasBody": true,
    "hasQuery": false,
    "nonEnvelope": false
  },
  {
    "namespace": "agentIntegrations",
    "command": "financial-apis-commodity",
    "method": "financialApisCommodity",
    "verb": "POST",
    "path": "/agent-integrations/financial-apis/commodity",
    "pathParams": [],
    "params": [
      {
        "name": "body",
        "role": "body"
      }
    ],
    "hasBody": true,
    "hasQuery": false,
    "nonEnvelope": false
  },
  {
    "namespace": "agentIntegrations",
    "command": "financial-apis-crypto-series",
    "method": "financialApisCryptoSeries",
    "verb": "POST",
    "path": "/agent-integrations/financial-apis/crypto-series",
    "pathParams": [],
    "params": [
      {
        "name": "body",
        "role": "body"
      }
    ],
    "hasBody": true,
    "hasQuery": false,
    "nonEnvelope": false
  },
  {
    "namespace": "agentIntegrations",
    "command": "financial-apis-exchange-rate",
    "method": "financialApisExchangeRate",
    "verb": "POST",
    "path": "/agent-integrations/financial-apis/exchange-rate",
    "pathParams": [],
    "params": [
      {
        "name": "body",
        "role": "body"
      }
    ],
    "hasBody": true,
    "hasQuery": false,
    "nonEnvelope": false
  },
  {
    "namespace": "agentIntegrations",
    "command": "financial-apis-options",
    "method": "financialApisOptions",
    "verb": "POST",
    "path": "/agent-integrations/financial-apis/options",
    "pathParams": [],
    "params": [
      {
        "name": "body",
        "role": "body"
      }
    ],
    "hasBody": true,
    "hasQuery": false,
    "nonEnvelope": false
  },
  {
    "namespace": "agentIntegrations",
    "command": "financial-apis-quote",
    "method": "financialApisQuote",
    "verb": "POST",
    "path": "/agent-integrations/financial-apis/quote",
    "pathParams": [],
    "params": [
      {
        "name": "body",
        "role": "body"
      }
    ],
    "hasBody": true,
    "hasQuery": false,
    "nonEnvelope": false
  },
  {
    "namespace": "agentIntegrations",
    "command": "get-apify-run",
    "method": "getApifyRun",
    "verb": "GET",
    "path": "/agent-integrations/apify/runs/:runId",
    "pathParams": [
      "runId"
    ],
    "params": [
      {
        "name": "runId",
        "role": "positional"
      }
    ],
    "hasBody": false,
    "hasQuery": false,
    "nonEnvelope": false
  },
  {
    "namespace": "agentIntegrations",
    "command": "get-apify-run-results",
    "method": "getApifyRunResults",
    "verb": "GET",
    "path": "/agent-integrations/apify/runs/:runId/results",
    "pathParams": [
      "runId"
    ],
    "params": [
      {
        "name": "runId",
        "role": "positional"
      },
      {
        "name": "query",
        "role": "query"
      }
    ],
    "hasBody": false,
    "hasQuery": true,
    "nonEnvelope": false
  },
  {
    "namespace": "agentIntegrations",
    "command": "get-file",
    "method": "getFile",
    "verb": "GET",
    "path": "/agent-integrations/file-storage/files/:fileId",
    "pathParams": [
      "fileId"
    ],
    "params": [
      {
        "name": "fileId",
        "role": "positional"
      }
    ],
    "hasBody": false,
    "hasQuery": false,
    "nonEnvelope": false
  },
  {
    "namespace": "agentIntegrations",
    "command": "get-file-storage-usage",
    "method": "getFileStorageUsage",
    "verb": "GET",
    "path": "/agent-integrations/file-storage/usage",
    "pathParams": [],
    "params": [],
    "hasBody": false,
    "hasQuery": false,
    "nonEnvelope": false
  },
  {
    "namespace": "agentIntegrations",
    "command": "get-history-reward-status",
    "method": "getHistoryRewardStatus",
    "verb": "GET",
    "path": "/agent-integrations/history-rewards/status",
    "pathParams": [],
    "params": [],
    "hasBody": false,
    "hasQuery": false,
    "nonEnvelope": false
  },
  {
    "namespace": "agentIntegrations",
    "command": "get-media-generation-request",
    "method": "getMediaGenerationRequest",
    "verb": "GET",
    "path": "/agent-integrations/media-generation/requests/:requestId",
    "pathParams": [
      "requestId"
    ],
    "params": [
      {
        "name": "requestId",
        "role": "positional"
      }
    ],
    "hasBody": false,
    "hasQuery": false,
    "nonEnvelope": false
  },
  {
    "namespace": "agentIntegrations",
    "command": "get-parallel-dataset",
    "method": "getParallelDataset",
    "verb": "GET",
    "path": "/agent-integrations/parallel/dataset/:findallId",
    "pathParams": [
      "findallId"
    ],
    "params": [
      {
        "name": "findallId",
        "role": "positional"
      }
    ],
    "hasBody": false,
    "hasQuery": false,
    "nonEnvelope": false
  },
  {
    "namespace": "agentIntegrations",
    "command": "get-parallel-dataset-result",
    "method": "getParallelDatasetResult",
    "verb": "GET",
    "path": "/agent-integrations/parallel/dataset/:findallId/result",
    "pathParams": [
      "findallId"
    ],
    "params": [
      {
        "name": "findallId",
        "role": "positional"
      }
    ],
    "hasBody": false,
    "hasQuery": false,
    "nonEnvelope": false
  },
  {
    "namespace": "agentIntegrations",
    "command": "get-parallel-research",
    "method": "getParallelResearch",
    "verb": "GET",
    "path": "/agent-integrations/parallel/research/:runId",
    "pathParams": [
      "runId"
    ],
    "params": [
      {
        "name": "runId",
        "role": "positional"
      }
    ],
    "hasBody": false,
    "hasQuery": false,
    "nonEnvelope": false
  },
  {
    "namespace": "agentIntegrations",
    "command": "get-parallel-research-result",
    "method": "getParallelResearchResult",
    "verb": "GET",
    "path": "/agent-integrations/parallel/research/:runId/result",
    "pathParams": [
      "runId"
    ],
    "params": [
      {
        "name": "runId",
        "role": "positional"
      },
      {
        "name": "query",
        "role": "query"
      }
    ],
    "hasBody": false,
    "hasQuery": true,
    "nonEnvelope": false
  },
  {
    "namespace": "agentIntegrations",
    "command": "get-pricing",
    "method": "getPricing",
    "verb": "GET",
    "path": "/agent-integrations/pricing",
    "pathParams": [],
    "params": [],
    "hasBody": false,
    "hasQuery": false,
    "nonEnvelope": false
  },
  {
    "namespace": "agentIntegrations",
    "command": "get-public-file",
    "method": "getPublicFile",
    "verb": "GET",
    "path": "/agent-integrations/file-storage/public/:fileId",
    "pathParams": [
      "fileId"
    ],
    "params": [
      {
        "name": "fileId",
        "role": "positional"
      }
    ],
    "hasBody": false,
    "hasQuery": false,
    "nonEnvelope": false
  },
  {
    "namespace": "agentIntegrations",
    "command": "get-recall-calendar-status",
    "method": "getRecallCalendarStatus",
    "verb": "GET",
    "path": "/agent-integrations/recall-calendar/status",
    "pathParams": [],
    "params": [],
    "hasBody": false,
    "hasQuery": false,
    "nonEnvelope": false
  },
  {
    "namespace": "agentIntegrations",
    "command": "google-places-details",
    "method": "googlePlacesDetails",
    "verb": "POST",
    "path": "/agent-integrations/google-places/details",
    "pathParams": [],
    "params": [
      {
        "name": "body",
        "role": "body"
      }
    ],
    "hasBody": true,
    "hasQuery": false,
    "nonEnvelope": false
  },
  {
    "namespace": "agentIntegrations",
    "command": "google-places-search",
    "method": "googlePlacesSearch",
    "verb": "POST",
    "path": "/agent-integrations/google-places/search",
    "pathParams": [],
    "params": [
      {
        "name": "body",
        "role": "body"
      }
    ],
    "hasBody": true,
    "hasQuery": false,
    "nonEnvelope": false
  },
  {
    "namespace": "agentIntegrations",
    "command": "link-file",
    "method": "linkFile",
    "verb": "POST",
    "path": "/agent-integrations/file-storage/files/:fileId/link",
    "pathParams": [
      "fileId"
    ],
    "params": [
      {
        "name": "fileId",
        "role": "positional"
      }
    ],
    "hasBody": false,
    "hasQuery": false,
    "nonEnvelope": false
  },
  {
    "namespace": "agentIntegrations",
    "command": "list-composio-available-triggers",
    "method": "listComposioAvailableTriggers",
    "verb": "GET",
    "path": "/agent-integrations/composio/triggers/available",
    "pathParams": [],
    "params": [
      {
        "name": "query",
        "role": "query"
      }
    ],
    "hasBody": false,
    "hasQuery": true,
    "nonEnvelope": false
  },
  {
    "namespace": "agentIntegrations",
    "command": "list-composio-connections",
    "method": "listComposioConnections",
    "verb": "GET",
    "path": "/agent-integrations/composio/connections",
    "pathParams": [],
    "params": [],
    "hasBody": false,
    "hasQuery": false,
    "nonEnvelope": false
  },
  {
    "namespace": "agentIntegrations",
    "command": "list-composio-toolkits",
    "method": "listComposioToolkits",
    "verb": "GET",
    "path": "/agent-integrations/composio/toolkits",
    "pathParams": [],
    "params": [],
    "hasBody": false,
    "hasQuery": false,
    "nonEnvelope": false
  },
  {
    "namespace": "agentIntegrations",
    "command": "list-composio-tools",
    "method": "listComposioTools",
    "verb": "GET",
    "path": "/agent-integrations/composio/tools",
    "pathParams": [],
    "params": [
      {
        "name": "query",
        "role": "query"
      }
    ],
    "hasBody": false,
    "hasQuery": true,
    "nonEnvelope": false
  },
  {
    "namespace": "agentIntegrations",
    "command": "list-composio-triggers",
    "method": "listComposioTriggers",
    "verb": "GET",
    "path": "/agent-integrations/composio/triggers",
    "pathParams": [],
    "params": [
      {
        "name": "query",
        "role": "query"
      }
    ],
    "hasBody": false,
    "hasQuery": true,
    "nonEnvelope": false
  },
  {
    "namespace": "agentIntegrations",
    "command": "list-crypto-routes",
    "method": "listCryptoRoutes",
    "verb": "GET",
    "path": "/agent-integrations/crypto/routes",
    "pathParams": [],
    "params": [],
    "hasBody": false,
    "hasQuery": false,
    "nonEnvelope": false
  },
  {
    "namespace": "agentIntegrations",
    "command": "list-files",
    "method": "listFiles",
    "verb": "GET",
    "path": "/agent-integrations/file-storage/files",
    "pathParams": [],
    "params": [
      {
        "name": "query",
        "role": "query"
      }
    ],
    "hasBody": false,
    "hasQuery": true,
    "nonEnvelope": false
  },
  {
    "namespace": "agentIntegrations",
    "command": "list-media-generation-models",
    "method": "listMediaGenerationModels",
    "verb": "GET",
    "path": "/agent-integrations/media-generation/models",
    "pathParams": [],
    "params": [
      {
        "name": "query",
        "role": "query"
      }
    ],
    "hasBody": false,
    "hasQuery": true,
    "nonEnvelope": false
  },
  {
    "namespace": "agentIntegrations",
    "command": "list-recall-calendar-meetings",
    "method": "listRecallCalendarMeetings",
    "verb": "GET",
    "path": "/agent-integrations/recall-calendar/meetings",
    "pathParams": [],
    "params": [],
    "hasBody": false,
    "hasQuery": false,
    "nonEnvelope": false
  },
  {
    "namespace": "agentIntegrations",
    "command": "media-generation-images",
    "method": "mediaGenerationImages",
    "verb": "POST",
    "path": "/agent-integrations/media-generation/images",
    "pathParams": [],
    "params": [
      {
        "name": "body",
        "role": "body"
      }
    ],
    "hasBody": true,
    "hasQuery": false,
    "nonEnvelope": false
  },
  {
    "namespace": "agentIntegrations",
    "command": "media-generation-videos",
    "method": "mediaGenerationVideos",
    "verb": "POST",
    "path": "/agent-integrations/media-generation/videos",
    "pathParams": [],
    "params": [
      {
        "name": "body",
        "role": "body"
      }
    ],
    "hasBody": true,
    "hasQuery": false,
    "nonEnvelope": false
  },
  {
    "namespace": "agentIntegrations",
    "command": "parallel-chat",
    "method": "parallelChat",
    "verb": "POST",
    "path": "/agent-integrations/parallel/chat",
    "pathParams": [],
    "params": [
      {
        "name": "body",
        "role": "body"
      }
    ],
    "hasBody": true,
    "hasQuery": false,
    "nonEnvelope": false
  },
  {
    "namespace": "agentIntegrations",
    "command": "parallel-dataset",
    "method": "parallelDataset",
    "verb": "POST",
    "path": "/agent-integrations/parallel/dataset",
    "pathParams": [],
    "params": [
      {
        "name": "body",
        "role": "body"
      }
    ],
    "hasBody": true,
    "hasQuery": false,
    "nonEnvelope": false
  },
  {
    "namespace": "agentIntegrations",
    "command": "parallel-enrich",
    "method": "parallelEnrich",
    "verb": "POST",
    "path": "/agent-integrations/parallel/enrich",
    "pathParams": [],
    "params": [
      {
        "name": "body",
        "role": "body"
      }
    ],
    "hasBody": true,
    "hasQuery": false,
    "nonEnvelope": false
  },
  {
    "namespace": "agentIntegrations",
    "command": "parallel-extract",
    "method": "parallelExtract",
    "verb": "POST",
    "path": "/agent-integrations/parallel/extract",
    "pathParams": [],
    "params": [
      {
        "name": "body",
        "role": "body"
      }
    ],
    "hasBody": true,
    "hasQuery": false,
    "nonEnvelope": false
  },
  {
    "namespace": "agentIntegrations",
    "command": "parallel-research",
    "method": "parallelResearch",
    "verb": "POST",
    "path": "/agent-integrations/parallel/research",
    "pathParams": [],
    "params": [
      {
        "name": "body",
        "role": "body"
      }
    ],
    "hasBody": true,
    "hasQuery": false,
    "nonEnvelope": false
  },
  {
    "namespace": "agentIntegrations",
    "command": "parallel-search",
    "method": "parallelSearch",
    "verb": "POST",
    "path": "/agent-integrations/parallel/search",
    "pathParams": [],
    "params": [
      {
        "name": "body",
        "role": "body"
      }
    ],
    "hasBody": true,
    "hasQuery": false,
    "nonEnvelope": false
  },
  {
    "namespace": "agentIntegrations",
    "command": "recall-calendar-o-auth-complete",
    "method": "recallCalendarOAuthComplete",
    "verb": "GET",
    "path": "/agent-integrations/recall-calendar/oauth-complete",
    "pathParams": [],
    "params": [
      {
        "name": "query",
        "role": "query"
      }
    ],
    "hasBody": false,
    "hasQuery": true,
    "nonEnvelope": false
  },
  {
    "namespace": "agentIntegrations",
    "command": "run-apify-actor",
    "method": "runApifyActor",
    "verb": "POST",
    "path": "/agent-integrations/apify/run",
    "pathParams": [],
    "params": [
      {
        "name": "body",
        "role": "body"
      }
    ],
    "hasBody": true,
    "hasQuery": false,
    "nonEnvelope": false
  },
  {
    "namespace": "agentIntegrations",
    "command": "tenor-search",
    "method": "tenorSearch",
    "verb": "POST",
    "path": "/agent-integrations/tenor/search",
    "pathParams": [],
    "params": [
      {
        "name": "body",
        "role": "body"
      }
    ],
    "hasBody": true,
    "hasQuery": false,
    "nonEnvelope": false
  },
  {
    "namespace": "agentIntegrations",
    "command": "twilio-call",
    "method": "twilioCall",
    "verb": "POST",
    "path": "/agent-integrations/twilio/call",
    "pathParams": [],
    "params": [
      {
        "name": "body",
        "role": "body"
      }
    ],
    "hasBody": true,
    "hasQuery": false,
    "nonEnvelope": false
  },
  {
    "namespace": "agentIntegrations",
    "command": "twilio-incoming-call-webhook",
    "method": "twilioIncomingCallWebhook",
    "verb": "POST",
    "path": "/agent-integrations/twilio/webhooks/incoming-call/:userId",
    "pathParams": [
      "userId"
    ],
    "params": [
      {
        "name": "userId",
        "role": "positional"
      },
      {
        "name": "body",
        "role": "body"
      }
    ],
    "hasBody": true,
    "hasQuery": false,
    "nonEnvelope": false
  },
  {
    "namespace": "agentIntegrations",
    "command": "twilio-status-webhook",
    "method": "twilioStatusWebhook",
    "verb": "POST",
    "path": "/agent-integrations/twilio/webhooks/status/:userId",
    "pathParams": [
      "userId"
    ],
    "params": [
      {
        "name": "userId",
        "role": "positional"
      },
      {
        "name": "body",
        "role": "body"
      }
    ],
    "hasBody": true,
    "hasQuery": false,
    "nonEnvelope": false
  },
  {
    "namespace": "agentIntegrations",
    "command": "update-file",
    "method": "updateFile",
    "verb": "PATCH",
    "path": "/agent-integrations/file-storage/files/:fileId",
    "pathParams": [
      "fileId"
    ],
    "params": [
      {
        "name": "fileId",
        "role": "positional"
      },
      {
        "name": "body",
        "role": "body"
      }
    ],
    "hasBody": true,
    "hasQuery": false,
    "nonEnvelope": false
  },
  {
    "namespace": "agentIntegrations",
    "command": "upload-file",
    "method": "uploadFile",
    "verb": "POST",
    "path": "/agent-integrations/file-storage/files",
    "pathParams": [],
    "params": [
      {
        "name": "body",
        "role": "body"
      }
    ],
    "hasBody": true,
    "hasQuery": false,
    "nonEnvelope": false
  },
  {
    "namespace": "agentIntegrations",
    "command": "upload-history-reward",
    "method": "uploadHistoryReward",
    "verb": "POST",
    "path": "/agent-integrations/history-rewards/uploads",
    "pathParams": [],
    "params": [
      {
        "name": "body",
        "role": "body"
      }
    ],
    "hasBody": true,
    "hasQuery": false,
    "nonEnvelope": false
  },
  {
    "namespace": "announcements",
    "command": "get-latest-announcements",
    "method": "getLatestAnnouncements",
    "verb": "GET",
    "path": "/announcements/latest",
    "pathParams": [],
    "params": [],
    "hasBody": false,
    "hasQuery": false,
    "nonEnvelope": false
  },
  {
    "namespace": "apiKeys",
    "command": "create-api-key",
    "method": "createApiKey",
    "verb": "POST",
    "path": "/api-keys",
    "pathParams": [],
    "params": [
      {
        "name": "body",
        "role": "body"
      }
    ],
    "hasBody": true,
    "hasQuery": false,
    "nonEnvelope": false
  },
  {
    "namespace": "apiKeys",
    "command": "delete-api-key",
    "method": "deleteApiKey",
    "verb": "DELETE",
    "path": "/api-keys/:keyId",
    "pathParams": [
      "keyId"
    ],
    "params": [
      {
        "name": "keyId",
        "role": "positional"
      }
    ],
    "hasBody": false,
    "hasQuery": false,
    "nonEnvelope": false
  },
  {
    "namespace": "apiKeys",
    "command": "list-api-keys",
    "method": "listApiKeys",
    "verb": "GET",
    "path": "/api-keys",
    "pathParams": [],
    "params": [],
    "hasBody": false,
    "hasQuery": false,
    "nonEnvelope": false
  },
  {
    "namespace": "auth",
    "command": "consume-login-token",
    "method": "consumeLoginToken",
    "verb": "POST",
    "path": "/auth/login-token/consume",
    "pathParams": [],
    "params": [
      {
        "name": "body",
        "role": "body"
      }
    ],
    "hasBody": true,
    "hasQuery": false,
    "nonEnvelope": false
  },
  {
    "namespace": "auth",
    "command": "create-channel-link-token",
    "method": "createChannelLinkToken",
    "verb": "POST",
    "path": "/auth/channels/:channel/link-token",
    "pathParams": [
      "channel"
    ],
    "params": [
      {
        "name": "channel",
        "role": "positional"
      }
    ],
    "hasBody": false,
    "hasQuery": false,
    "nonEnvelope": false
  },
  {
    "namespace": "auth",
    "command": "create-integration-token",
    "method": "createIntegrationToken",
    "verb": "POST",
    "path": "/auth/integrations/:integrationId/tokens",
    "pathParams": [
      "integrationId"
    ],
    "params": [
      {
        "name": "integrationId",
        "role": "positional"
      },
      {
        "name": "body",
        "role": "body"
      }
    ],
    "hasBody": true,
    "hasQuery": false,
    "nonEnvelope": false
  },
  {
    "namespace": "auth",
    "command": "delete-integration",
    "method": "deleteIntegration",
    "verb": "DELETE",
    "path": "/auth/integrations/:integrationId",
    "pathParams": [
      "integrationId"
    ],
    "params": [
      {
        "name": "integrationId",
        "role": "positional"
      }
    ],
    "hasBody": false,
    "hasQuery": false,
    "nonEnvelope": false
  },
  {
    "namespace": "auth",
    "command": "list-integrations",
    "method": "listIntegrations",
    "verb": "GET",
    "path": "/auth/integrations",
    "pathParams": [],
    "params": [],
    "hasBody": false,
    "hasQuery": false,
    "nonEnvelope": false
  },
  {
    "namespace": "auth",
    "command": "me",
    "method": "me",
    "verb": "GET",
    "path": "/auth/me",
    "pathParams": [],
    "params": [],
    "hasBody": false,
    "hasQuery": false,
    "nonEnvelope": false
  },
  {
    "namespace": "auth",
    "command": "oauth-callback",
    "method": "oauthCallback",
    "verb": "GET",
    "path": "/auth/:provider/callback",
    "pathParams": [
      "provider"
    ],
    "params": [
      {
        "name": "provider",
        "role": "positional"
      }
    ],
    "hasBody": false,
    "hasQuery": false,
    "nonEnvelope": false
  },
  {
    "namespace": "auth",
    "command": "oauth-connect",
    "method": "oauthConnect",
    "verb": "GET",
    "path": "/auth/:provider/connect",
    "pathParams": [
      "provider"
    ],
    "params": [
      {
        "name": "provider",
        "role": "positional"
      },
      {
        "name": "query",
        "role": "query"
      }
    ],
    "hasBody": false,
    "hasQuery": true,
    "nonEnvelope": false
  },
  {
    "namespace": "auth",
    "command": "oauth-login",
    "method": "oauthLogin",
    "verb": "GET",
    "path": "/auth/:provider/login",
    "pathParams": [
      "provider"
    ],
    "params": [
      {
        "name": "provider",
        "role": "positional"
      },
      {
        "name": "query",
        "role": "query"
      }
    ],
    "hasBody": false,
    "hasQuery": true,
    "nonEnvelope": false
  },
  {
    "namespace": "auth",
    "command": "send-email-link",
    "method": "sendEmailLink",
    "verb": "POST",
    "path": "/auth/email/send-link",
    "pathParams": [],
    "params": [
      {
        "name": "body",
        "role": "body"
      }
    ],
    "hasBody": true,
    "hasQuery": false,
    "nonEnvelope": false
  },
  {
    "namespace": "auth",
    "command": "verify-email",
    "method": "verifyEmail",
    "verb": "GET",
    "path": "/auth/email/verify",
    "pathParams": [],
    "params": [
      {
        "name": "token",
        "role": "positional"
      }
    ],
    "hasBody": false,
    "hasQuery": false,
    "nonEnvelope": false
  },
  {
    "namespace": "budgets",
    "command": "create-seat",
    "method": "createSeat",
    "verb": "POST",
    "path": "/budgets/seats",
    "pathParams": [],
    "params": [
      {
        "name": "body",
        "role": "body"
      }
    ],
    "hasBody": true,
    "hasQuery": false,
    "nonEnvelope": false
  },
  {
    "namespace": "budgets",
    "command": "delete-seat",
    "method": "deleteSeat",
    "verb": "DELETE",
    "path": "/budgets/seats/:seatId",
    "pathParams": [
      "seatId"
    ],
    "params": [
      {
        "name": "seatId",
        "role": "positional"
      }
    ],
    "hasBody": false,
    "hasQuery": false,
    "nonEnvelope": false
  },
  {
    "namespace": "budgets",
    "command": "get-budgets",
    "method": "getBudgets",
    "verb": "GET",
    "path": "/budgets",
    "pathParams": [],
    "params": [],
    "hasBody": false,
    "hasQuery": false,
    "nonEnvelope": false
  },
  {
    "namespace": "budgets",
    "command": "update-seat",
    "method": "updateSeat",
    "verb": "PATCH",
    "path": "/budgets/seats/:seatId",
    "pathParams": [
      "seatId"
    ],
    "params": [
      {
        "name": "seatId",
        "role": "positional"
      },
      {
        "name": "body",
        "role": "body"
      }
    ],
    "hasBody": true,
    "hasQuery": false,
    "nonEnvelope": false
  },
  {
    "namespace": "channels",
    "command": "add-reaction",
    "method": "addReaction",
    "verb": "POST",
    "path": "/channels/:channel/reactions",
    "pathParams": [
      "channel"
    ],
    "params": [
      {
        "name": "channel",
        "role": "positional"
      },
      {
        "name": "body",
        "role": "body"
      }
    ],
    "hasBody": true,
    "hasQuery": false,
    "nonEnvelope": false
  },
  {
    "namespace": "channels",
    "command": "create-thread",
    "method": "createThread",
    "verb": "POST",
    "path": "/channels/:channel/threads",
    "pathParams": [
      "channel"
    ],
    "params": [
      {
        "name": "channel",
        "role": "positional"
      },
      {
        "name": "body",
        "role": "body"
      }
    ],
    "hasBody": true,
    "hasQuery": false,
    "nonEnvelope": false
  },
  {
    "namespace": "channels",
    "command": "delete-message",
    "method": "deleteMessage",
    "verb": "DELETE",
    "path": "/channels/:channel/messages/:messageId",
    "pathParams": [
      "channel",
      "messageId"
    ],
    "params": [
      {
        "name": "channel",
        "role": "positional"
      },
      {
        "name": "messageId",
        "role": "positional"
      }
    ],
    "hasBody": false,
    "hasQuery": false,
    "nonEnvelope": false
  },
  {
    "namespace": "channels",
    "command": "list-threads",
    "method": "listThreads",
    "verb": "GET",
    "path": "/channels/:channel/threads",
    "pathParams": [
      "channel"
    ],
    "params": [
      {
        "name": "channel",
        "role": "positional"
      },
      {
        "name": "query",
        "role": "query"
      }
    ],
    "hasBody": false,
    "hasQuery": true,
    "nonEnvelope": false
  },
  {
    "namespace": "channels",
    "command": "send-message",
    "method": "sendMessage",
    "verb": "POST",
    "path": "/channels/:channel/messages",
    "pathParams": [
      "channel"
    ],
    "params": [
      {
        "name": "channel",
        "role": "positional"
      },
      {
        "name": "body",
        "role": "body"
      }
    ],
    "hasBody": true,
    "hasQuery": false,
    "nonEnvelope": false
  },
  {
    "namespace": "channels",
    "command": "send-typing",
    "method": "sendTyping",
    "verb": "POST",
    "path": "/channels/:channel/typing",
    "pathParams": [
      "channel"
    ],
    "params": [
      {
        "name": "channel",
        "role": "positional"
      },
      {
        "name": "body",
        "role": "body"
      }
    ],
    "hasBody": true,
    "hasQuery": false,
    "nonEnvelope": false
  },
  {
    "namespace": "channels",
    "command": "update-thread",
    "method": "updateThread",
    "verb": "PATCH",
    "path": "/channels/:channel/threads/:threadId",
    "pathParams": [
      "channel",
      "threadId"
    ],
    "params": [
      {
        "name": "channel",
        "role": "positional"
      },
      {
        "name": "threadId",
        "role": "positional"
      },
      {
        "name": "body",
        "role": "body"
      }
    ],
    "hasBody": true,
    "hasQuery": false,
    "nonEnvelope": false
  },
  {
    "namespace": "coupons",
    "command": "list-my-coupons",
    "method": "listMyCoupons",
    "verb": "GET",
    "path": "/coupons/me",
    "pathParams": [],
    "params": [],
    "hasBody": false,
    "hasQuery": false,
    "nonEnvelope": false
  },
  {
    "namespace": "coupons",
    "command": "redeem-coupon",
    "method": "redeemCoupon",
    "verb": "POST",
    "path": "/coupons/redeem",
    "pathParams": [],
    "params": [
      {
        "name": "body",
        "role": "body"
      }
    ],
    "hasBody": true,
    "hasQuery": false,
    "nonEnvelope": false
  },
  {
    "namespace": "feedback",
    "command": "comment-feedback",
    "method": "commentFeedback",
    "verb": "POST",
    "path": "/feedback/:id/comments",
    "pathParams": [
      "id"
    ],
    "params": [
      {
        "name": "id",
        "role": "positional"
      },
      {
        "name": "body",
        "role": "body"
      }
    ],
    "hasBody": true,
    "hasQuery": false,
    "nonEnvelope": false
  },
  {
    "namespace": "feedback",
    "command": "create-feedback",
    "method": "createFeedback",
    "verb": "POST",
    "path": "/feedback",
    "pathParams": [],
    "params": [
      {
        "name": "body",
        "role": "body"
      }
    ],
    "hasBody": true,
    "hasQuery": false,
    "nonEnvelope": false
  },
  {
    "namespace": "feedback",
    "command": "get-feedback",
    "method": "getFeedback",
    "verb": "GET",
    "path": "/feedback/:id",
    "pathParams": [
      "id"
    ],
    "params": [
      {
        "name": "id",
        "role": "positional"
      }
    ],
    "hasBody": false,
    "hasQuery": false,
    "nonEnvelope": false
  },
  {
    "namespace": "feedback",
    "command": "ingest-feedback",
    "method": "ingestFeedback",
    "verb": "POST",
    "path": "/feedback/ingest",
    "pathParams": [],
    "params": [
      {
        "name": "body",
        "role": "body"
      }
    ],
    "hasBody": true,
    "hasQuery": false,
    "nonEnvelope": false
  },
  {
    "namespace": "feedback",
    "command": "list-feedback",
    "method": "listFeedback",
    "verb": "GET",
    "path": "/feedback",
    "pathParams": [],
    "params": [
      {
        "name": "query",
        "role": "query"
      }
    ],
    "hasBody": false,
    "hasQuery": true,
    "nonEnvelope": false
  },
  {
    "namespace": "feedback",
    "command": "vote-feedback",
    "method": "voteFeedback",
    "verb": "POST",
    "path": "/feedback/:id/vote",
    "pathParams": [
      "id"
    ],
    "params": [
      {
        "name": "id",
        "role": "positional"
      },
      {
        "name": "body",
        "role": "body"
      }
    ],
    "hasBody": true,
    "hasQuery": false,
    "nonEnvelope": false
  },
  {
    "namespace": "health",
    "command": "check",
    "method": "check",
    "verb": "GET",
    "path": "/",
    "pathParams": [],
    "params": [],
    "hasBody": false,
    "hasQuery": false,
    "nonEnvelope": false
  },
  {
    "namespace": "inference",
    "command": "create-chat-completion",
    "method": "createChatCompletion",
    "verb": "POST",
    "path": "/openai/v1/chat/completions",
    "pathParams": [],
    "params": [
      {
        "name": "body",
        "role": "body"
      }
    ],
    "hasBody": true,
    "hasQuery": false,
    "nonEnvelope": true
  },
  {
    "namespace": "inference",
    "command": "create-completion",
    "method": "createCompletion",
    "verb": "POST",
    "path": "/openai/v1/completions",
    "pathParams": [],
    "params": [
      {
        "name": "body",
        "role": "body"
      }
    ],
    "hasBody": true,
    "hasQuery": false,
    "nonEnvelope": true
  },
  {
    "namespace": "inference",
    "command": "create-embeddings",
    "method": "createEmbeddings",
    "verb": "POST",
    "path": "/openai/v1/embeddings",
    "pathParams": [],
    "params": [
      {
        "name": "body",
        "role": "body"
      }
    ],
    "hasBody": true,
    "hasQuery": false,
    "nonEnvelope": true
  },
  {
    "namespace": "inference",
    "command": "create-speech",
    "method": "createSpeech",
    "verb": "POST",
    "path": "/openai/v1/audio/speech",
    "pathParams": [],
    "params": [
      {
        "name": "body",
        "role": "body"
      }
    ],
    "hasBody": true,
    "hasQuery": false,
    "nonEnvelope": true
  },
  {
    "namespace": "inference",
    "command": "create-transcription",
    "method": "createTranscription",
    "verb": "POST",
    "path": "/openai/v1/audio/transcriptions",
    "pathParams": [],
    "params": [
      {
        "name": "body",
        "role": "body"
      }
    ],
    "hasBody": true,
    "hasQuery": false,
    "nonEnvelope": true
  },
  {
    "namespace": "inference",
    "command": "list-models",
    "method": "listModels",
    "verb": "GET",
    "path": "/openai/v1/models",
    "pathParams": [],
    "params": [
      {
        "name": "query",
        "role": "query"
      }
    ],
    "hasBody": false,
    "hasQuery": true,
    "nonEnvelope": true
  },
  {
    "namespace": "invite",
    "command": "get-invite-status",
    "method": "getInviteStatus",
    "verb": "GET",
    "path": "/invite/status",
    "pathParams": [],
    "params": [
      {
        "name": "query",
        "role": "query"
      }
    ],
    "hasBody": false,
    "hasQuery": true,
    "nonEnvelope": false
  },
  {
    "namespace": "invite",
    "command": "list-my-codes",
    "method": "listMyCodes",
    "verb": "GET",
    "path": "/invite/my-codes",
    "pathParams": [],
    "params": [],
    "hasBody": false,
    "hasQuery": false,
    "nonEnvelope": false
  },
  {
    "namespace": "invite",
    "command": "redeem-invite",
    "method": "redeemInvite",
    "verb": "POST",
    "path": "/invite/redeem",
    "pathParams": [],
    "params": [
      {
        "name": "body",
        "role": "body"
      }
    ],
    "hasBody": true,
    "hasQuery": false,
    "nonEnvelope": false
  },
  {
    "namespace": "mascots",
    "command": "get-demo",
    "method": "getDemo",
    "verb": "GET",
    "path": "/mascots/demo",
    "pathParams": [],
    "params": [],
    "hasBody": false,
    "hasQuery": false,
    "nonEnvelope": false
  },
  {
    "namespace": "mascots",
    "command": "get-mascot",
    "method": "getMascot",
    "verb": "GET",
    "path": "/mascots/:id",
    "pathParams": [
      "id"
    ],
    "params": [
      {
        "name": "id",
        "role": "positional"
      }
    ],
    "hasBody": false,
    "hasQuery": false,
    "nonEnvelope": false
  },
  {
    "namespace": "mascots",
    "command": "get-mascot-riv",
    "method": "getMascotRiv",
    "verb": "GET",
    "path": "/mascots/:id/riv",
    "pathParams": [
      "id"
    ],
    "params": [
      {
        "name": "id",
        "role": "positional"
      }
    ],
    "hasBody": false,
    "hasQuery": false,
    "nonEnvelope": false
  },
  {
    "namespace": "mascots",
    "command": "join-meeting",
    "method": "joinMeeting",
    "verb": "POST",
    "path": "/mascots/join-meeting",
    "pathParams": [],
    "params": [
      {
        "name": "body",
        "role": "body"
      }
    ],
    "hasBody": true,
    "hasQuery": false,
    "nonEnvelope": false
  },
  {
    "namespace": "mascots",
    "command": "list-mascots",
    "method": "listMascots",
    "verb": "GET",
    "path": "/mascots",
    "pathParams": [],
    "params": [],
    "hasBody": false,
    "hasQuery": false,
    "nonEnvelope": false
  },
  {
    "namespace": "mascots",
    "command": "list-meetings",
    "method": "listMeetings",
    "verb": "GET",
    "path": "/mascots/meetings",
    "pathParams": [],
    "params": [
      {
        "name": "query",
        "role": "query"
      }
    ],
    "hasBody": false,
    "hasQuery": true,
    "nonEnvelope": false
  },
  {
    "namespace": "medulla",
    "command": "abort-session",
    "method": "abortSession",
    "verb": "POST",
    "path": "/medulla/v1/sessions/:id/abort",
    "pathParams": [
      "id"
    ],
    "params": [
      {
        "name": "id",
        "role": "positional"
      }
    ],
    "hasBody": false,
    "hasQuery": false,
    "nonEnvelope": false
  },
  {
    "namespace": "medulla",
    "command": "create-session",
    "method": "createSession",
    "verb": "POST",
    "path": "/medulla/v1/sessions",
    "pathParams": [],
    "params": [
      {
        "name": "body",
        "role": "body"
      }
    ],
    "hasBody": true,
    "hasQuery": false,
    "nonEnvelope": false
  },
  {
    "namespace": "medulla",
    "command": "create-task",
    "method": "createTask",
    "verb": "POST",
    "path": "/medulla/v1/tasks",
    "pathParams": [],
    "params": [
      {
        "name": "body",
        "role": "body"
      }
    ],
    "hasBody": true,
    "hasQuery": false,
    "nonEnvelope": false
  },
  {
    "namespace": "medulla",
    "command": "create-task-source",
    "method": "createTaskSource",
    "verb": "POST",
    "path": "/medulla/v1/tasks/sources",
    "pathParams": [],
    "params": [
      {
        "name": "body",
        "role": "body"
      }
    ],
    "hasBody": true,
    "hasQuery": false,
    "nonEnvelope": false
  },
  {
    "namespace": "medulla",
    "command": "delete-session",
    "method": "deleteSession",
    "verb": "DELETE",
    "path": "/medulla/v1/sessions/:id",
    "pathParams": [
      "id"
    ],
    "params": [
      {
        "name": "id",
        "role": "positional"
      }
    ],
    "hasBody": false,
    "hasQuery": false,
    "nonEnvelope": false
  },
  {
    "namespace": "medulla",
    "command": "delete-task",
    "method": "deleteTask",
    "verb": "DELETE",
    "path": "/medulla/v1/tasks/:id",
    "pathParams": [
      "id"
    ],
    "params": [
      {
        "name": "id",
        "role": "positional"
      }
    ],
    "hasBody": false,
    "hasQuery": false,
    "nonEnvelope": false
  },
  {
    "namespace": "medulla",
    "command": "delete-task-source",
    "method": "deleteTaskSource",
    "verb": "DELETE",
    "path": "/medulla/v1/tasks/sources/:id",
    "pathParams": [
      "id"
    ],
    "params": [
      {
        "name": "id",
        "role": "positional"
      }
    ],
    "hasBody": false,
    "hasQuery": false,
    "nonEnvelope": false
  },
  {
    "namespace": "medulla",
    "command": "get-roster",
    "method": "getRoster",
    "verb": "GET",
    "path": "/medulla/v1/roster",
    "pathParams": [],
    "params": [],
    "hasBody": false,
    "hasQuery": false,
    "nonEnvelope": false
  },
  {
    "namespace": "medulla",
    "command": "get-routing-strategy",
    "method": "getRoutingStrategy",
    "verb": "GET",
    "path": "/medulla/v1/routing/strategy",
    "pathParams": [],
    "params": [],
    "hasBody": false,
    "hasQuery": false,
    "nonEnvelope": false
  },
  {
    "namespace": "medulla",
    "command": "get-session",
    "method": "getSession",
    "verb": "GET",
    "path": "/medulla/v1/sessions/:id",
    "pathParams": [
      "id"
    ],
    "params": [
      {
        "name": "id",
        "role": "positional"
      }
    ],
    "hasBody": false,
    "hasQuery": false,
    "nonEnvelope": false
  },
  {
    "namespace": "medulla",
    "command": "list-events",
    "method": "listEvents",
    "verb": "GET",
    "path": "/medulla/v1/sessions/:id/events",
    "pathParams": [
      "id"
    ],
    "params": [
      {
        "name": "id",
        "role": "positional"
      },
      {
        "name": "query",
        "role": "query"
      }
    ],
    "hasBody": false,
    "hasQuery": true,
    "nonEnvelope": false
  },
  {
    "namespace": "medulla",
    "command": "list-messages",
    "method": "listMessages",
    "verb": "GET",
    "path": "/medulla/v1/sessions/:id/messages",
    "pathParams": [
      "id"
    ],
    "params": [
      {
        "name": "id",
        "role": "positional"
      },
      {
        "name": "query",
        "role": "query"
      }
    ],
    "hasBody": false,
    "hasQuery": true,
    "nonEnvelope": false
  },
  {
    "namespace": "medulla",
    "command": "list-sessions",
    "method": "listSessions",
    "verb": "GET",
    "path": "/medulla/v1/sessions",
    "pathParams": [],
    "params": [],
    "hasBody": false,
    "hasQuery": false,
    "nonEnvelope": false
  },
  {
    "namespace": "medulla",
    "command": "list-task-sources",
    "method": "listTaskSources",
    "verb": "GET",
    "path": "/medulla/v1/tasks/sources",
    "pathParams": [],
    "params": [],
    "hasBody": false,
    "hasQuery": false,
    "nonEnvelope": false
  },
  {
    "namespace": "medulla",
    "command": "list-tasks",
    "method": "listTasks",
    "verb": "GET",
    "path": "/medulla/v1/tasks",
    "pathParams": [],
    "params": [],
    "hasBody": false,
    "hasQuery": false,
    "nonEnvelope": false
  },
  {
    "namespace": "medulla",
    "command": "send-message",
    "method": "sendMessage",
    "verb": "POST",
    "path": "/medulla/v1/sessions/:id/messages",
    "pathParams": [
      "id"
    ],
    "params": [
      {
        "name": "id",
        "role": "positional"
      },
      {
        "name": "body",
        "role": "body"
      },
      {
        "name": "query",
        "role": "query"
      }
    ],
    "hasBody": true,
    "hasQuery": true,
    "nonEnvelope": false
  },
  {
    "namespace": "medulla",
    "command": "stream-session",
    "method": "streamSession",
    "verb": "GET",
    "path": "/medulla/v1/sessions/:id/stream",
    "pathParams": [
      "id"
    ],
    "params": [
      {
        "name": "id",
        "role": "positional"
      },
      {
        "name": "query",
        "role": "query"
      }
    ],
    "hasBody": false,
    "hasQuery": true,
    "nonEnvelope": false
  },
  {
    "namespace": "medulla",
    "command": "sync-task-source",
    "method": "syncTaskSource",
    "verb": "POST",
    "path": "/medulla/v1/tasks/sources/:id/sync",
    "pathParams": [
      "id"
    ],
    "params": [
      {
        "name": "id",
        "role": "positional"
      }
    ],
    "hasBody": false,
    "hasQuery": false,
    "nonEnvelope": false
  },
  {
    "namespace": "medulla",
    "command": "update-routing-strategy",
    "method": "updateRoutingStrategy",
    "verb": "PUT",
    "path": "/medulla/v1/routing/strategy",
    "pathParams": [],
    "params": [
      {
        "name": "body",
        "role": "body"
      }
    ],
    "hasBody": true,
    "hasQuery": false,
    "nonEnvelope": false
  },
  {
    "namespace": "medulla",
    "command": "update-task",
    "method": "updateTask",
    "verb": "PATCH",
    "path": "/medulla/v1/tasks/:id",
    "pathParams": [
      "id"
    ],
    "params": [
      {
        "name": "id",
        "role": "positional"
      },
      {
        "name": "body",
        "role": "body"
      }
    ],
    "hasBody": true,
    "hasQuery": false,
    "nonEnvelope": false
  },
  {
    "namespace": "openCompany",
    "command": "create-instance",
    "method": "createInstance",
    "verb": "POST",
    "path": "/opencompany/instances",
    "pathParams": [],
    "params": [
      {
        "name": "body",
        "role": "body"
      }
    ],
    "hasBody": true,
    "hasQuery": false,
    "nonEnvelope": false
  },
  {
    "namespace": "openCompany",
    "command": "delete-custom-domain",
    "method": "deleteCustomDomain",
    "verb": "DELETE",
    "path": "/opencompany/instances/:slug/custom-domain",
    "pathParams": [
      "slug"
    ],
    "params": [
      {
        "name": "slug",
        "role": "positional"
      }
    ],
    "hasBody": false,
    "hasQuery": false,
    "nonEnvelope": false
  },
  {
    "namespace": "openCompany",
    "command": "delete-instance",
    "method": "deleteInstance",
    "verb": "DELETE",
    "path": "/opencompany/instances/:slug",
    "pathParams": [
      "slug"
    ],
    "params": [
      {
        "name": "slug",
        "role": "positional"
      },
      {
        "name": "query",
        "role": "query"
      }
    ],
    "hasBody": false,
    "hasQuery": true,
    "nonEnvelope": false
  },
  {
    "namespace": "openCompany",
    "command": "get-instance",
    "method": "getInstance",
    "verb": "GET",
    "path": "/opencompany/instances/:slug",
    "pathParams": [
      "slug"
    ],
    "params": [
      {
        "name": "slug",
        "role": "positional"
      }
    ],
    "hasBody": false,
    "hasQuery": false,
    "nonEnvelope": false
  },
  {
    "namespace": "openCompany",
    "command": "list-instances",
    "method": "listInstances",
    "verb": "GET",
    "path": "/opencompany/instances",
    "pathParams": [],
    "params": [],
    "hasBody": false,
    "hasQuery": false,
    "nonEnvelope": false
  },
  {
    "namespace": "openCompany",
    "command": "resume-instance",
    "method": "resumeInstance",
    "verb": "POST",
    "path": "/opencompany/instances/:slug/resume",
    "pathParams": [
      "slug"
    ],
    "params": [
      {
        "name": "slug",
        "role": "positional"
      }
    ],
    "hasBody": false,
    "hasQuery": false,
    "nonEnvelope": false
  },
  {
    "namespace": "openCompany",
    "command": "set-custom-domain",
    "method": "setCustomDomain",
    "verb": "PUT",
    "path": "/opencompany/instances/:slug/custom-domain",
    "pathParams": [
      "slug"
    ],
    "params": [
      {
        "name": "slug",
        "role": "positional"
      },
      {
        "name": "body",
        "role": "body"
      }
    ],
    "hasBody": true,
    "hasQuery": false,
    "nonEnvelope": false
  },
  {
    "namespace": "openCompany",
    "command": "suspend-instance",
    "method": "suspendInstance",
    "verb": "POST",
    "path": "/opencompany/instances/:slug/suspend",
    "pathParams": [
      "slug"
    ],
    "params": [
      {
        "name": "slug",
        "role": "positional"
      }
    ],
    "hasBody": false,
    "hasQuery": false,
    "nonEnvelope": false
  },
  {
    "namespace": "openCompany",
    "command": "verify-custom-domain",
    "method": "verifyCustomDomain",
    "verb": "POST",
    "path": "/opencompany/instances/:slug/custom-domain/verify",
    "pathParams": [
      "slug"
    ],
    "params": [
      {
        "name": "slug",
        "role": "positional"
      }
    ],
    "hasBody": false,
    "hasQuery": false,
    "nonEnvelope": false
  },
  {
    "namespace": "orchestration",
    "command": "continue-run",
    "method": "continueRun",
    "verb": "POST",
    "path": "/orchestration/v1/run/continue",
    "pathParams": [],
    "params": [
      {
        "name": "body",
        "role": "body"
      }
    ],
    "hasBody": true,
    "hasQuery": false,
    "nonEnvelope": false
  },
  {
    "namespace": "orchestration",
    "command": "get-session-state",
    "method": "getSessionState",
    "verb": "GET",
    "path": "/orchestration/v1/sessions/:id/state",
    "pathParams": [
      "id"
    ],
    "params": [
      {
        "name": "id",
        "role": "positional"
      }
    ],
    "hasBody": false,
    "hasQuery": false,
    "nonEnvelope": false
  },
  {
    "namespace": "orchestration",
    "command": "get-world-diff",
    "method": "getWorldDiff",
    "verb": "GET",
    "path": "/orchestration/v1/world-diff",
    "pathParams": [],
    "params": [
      {
        "name": "query",
        "role": "query"
      }
    ],
    "hasBody": false,
    "hasQuery": true,
    "nonEnvelope": false
  },
  {
    "namespace": "orchestration",
    "command": "ingest-event",
    "method": "ingestEvent",
    "verb": "POST",
    "path": "/orchestration/v1/events",
    "pathParams": [],
    "params": [
      {
        "name": "body",
        "role": "body"
      }
    ],
    "hasBody": true,
    "hasQuery": false,
    "nonEnvelope": false
  },
  {
    "namespace": "orchestration",
    "command": "list-session-messages",
    "method": "listSessionMessages",
    "verb": "GET",
    "path": "/orchestration/v1/sessions/:id/messages",
    "pathParams": [
      "id"
    ],
    "params": [
      {
        "name": "id",
        "role": "positional"
      },
      {
        "name": "query",
        "role": "query"
      }
    ],
    "hasBody": false,
    "hasQuery": true,
    "nonEnvelope": false
  },
  {
    "namespace": "orchestration",
    "command": "list-sessions",
    "method": "listSessions",
    "verb": "GET",
    "path": "/orchestration/v1/sessions",
    "pathParams": [],
    "params": [],
    "hasBody": false,
    "hasQuery": false,
    "nonEnvelope": false
  },
  {
    "namespace": "orchestration",
    "command": "post-world-diff",
    "method": "postWorldDiff",
    "verb": "POST",
    "path": "/orchestration/v1/world-diff",
    "pathParams": [],
    "params": [
      {
        "name": "body",
        "role": "body"
      }
    ],
    "hasBody": true,
    "hasQuery": false,
    "nonEnvelope": false
  },
  {
    "namespace": "orchestration",
    "command": "run",
    "method": "run",
    "verb": "POST",
    "path": "/orchestration/v1/run",
    "pathParams": [],
    "params": [
      {
        "name": "body",
        "role": "body"
      }
    ],
    "hasBody": true,
    "hasQuery": false,
    "nonEnvelope": false
  },
  {
    "namespace": "payments",
    "command": "create-auto-recharge-card-setup-intent",
    "method": "createAutoRechargeCardSetupIntent",
    "verb": "POST",
    "path": "/payments/credits/auto-recharge/cards/setup-intent",
    "pathParams": [],
    "params": [],
    "hasBody": false,
    "hasQuery": false,
    "nonEnvelope": false
  },
  {
    "namespace": "payments",
    "command": "create-coinbase-charge",
    "method": "createCoinbaseCharge",
    "verb": "POST",
    "path": "/payments/coinbase/charge",
    "pathParams": [],
    "params": [
      {
        "name": "body",
        "role": "body"
      }
    ],
    "hasBody": true,
    "hasQuery": false,
    "nonEnvelope": false
  },
  {
    "namespace": "payments",
    "command": "create-credit-top-up",
    "method": "createCreditTopUp",
    "verb": "POST",
    "path": "/payments/credits/top-up",
    "pathParams": [],
    "params": [
      {
        "name": "body",
        "role": "body"
      }
    ],
    "hasBody": true,
    "hasQuery": false,
    "nonEnvelope": false
  },
  {
    "namespace": "payments",
    "command": "create-stripe-portal-session",
    "method": "createStripePortalSession",
    "verb": "POST",
    "path": "/payments/stripe/portal",
    "pathParams": [],
    "params": [],
    "hasBody": false,
    "hasQuery": false,
    "nonEnvelope": false
  },
  {
    "namespace": "payments",
    "command": "delete-auto-recharge-card",
    "method": "deleteAutoRechargeCard",
    "verb": "DELETE",
    "path": "/payments/credits/auto-recharge/cards/:paymentMethodId",
    "pathParams": [
      "paymentMethodId"
    ],
    "params": [
      {
        "name": "paymentMethodId",
        "role": "positional"
      }
    ],
    "hasBody": false,
    "hasQuery": false,
    "nonEnvelope": false
  },
  {
    "namespace": "payments",
    "command": "get-auto-recharge",
    "method": "getAutoRecharge",
    "verb": "GET",
    "path": "/payments/credits/auto-recharge",
    "pathParams": [],
    "params": [],
    "hasBody": false,
    "hasQuery": false,
    "nonEnvelope": false
  },
  {
    "namespace": "payments",
    "command": "get-coinbase-charge",
    "method": "getCoinbaseCharge",
    "verb": "GET",
    "path": "/payments/coinbase/charge/:gatewayTransactionId",
    "pathParams": [
      "gatewayTransactionId"
    ],
    "params": [
      {
        "name": "gatewayTransactionId",
        "role": "positional"
      },
      {
        "name": "query",
        "role": "query"
      }
    ],
    "hasBody": false,
    "hasQuery": true,
    "nonEnvelope": false
  },
  {
    "namespace": "payments",
    "command": "get-credit-balance",
    "method": "getCreditBalance",
    "verb": "GET",
    "path": "/payments/credits/balance",
    "pathParams": [],
    "params": [],
    "hasBody": false,
    "hasQuery": false,
    "nonEnvelope": false
  },
  {
    "namespace": "payments",
    "command": "get-credit-top-up-cancel",
    "method": "getCreditTopUpCancel",
    "verb": "GET",
    "path": "/payments/credits/top-up/cancel",
    "pathParams": [],
    "params": [],
    "hasBody": false,
    "hasQuery": false,
    "nonEnvelope": false
  },
  {
    "namespace": "payments",
    "command": "get-credit-top-up-success",
    "method": "getCreditTopUpSuccess",
    "verb": "GET",
    "path": "/payments/credits/top-up/success",
    "pathParams": [],
    "params": [
      {
        "name": "query",
        "role": "query"
      }
    ],
    "hasBody": false,
    "hasQuery": true,
    "nonEnvelope": false
  },
  {
    "namespace": "payments",
    "command": "get-current-plan",
    "method": "getCurrentPlan",
    "verb": "GET",
    "path": "/payments/stripe/currentPlan",
    "pathParams": [],
    "params": [],
    "hasBody": false,
    "hasQuery": false,
    "nonEnvelope": false
  },
  {
    "namespace": "payments",
    "command": "get-stripe-checkout-return",
    "method": "getStripeCheckoutReturn",
    "verb": "GET",
    "path": "/payments/stripe/checkout/return",
    "pathParams": [],
    "params": [
      {
        "name": "query",
        "role": "query"
      }
    ],
    "hasBody": false,
    "hasQuery": true,
    "nonEnvelope": false
  },
  {
    "namespace": "payments",
    "command": "get-stripe-plans",
    "method": "getStripePlans",
    "verb": "GET",
    "path": "/payments/stripe/plans",
    "pathParams": [],
    "params": [],
    "hasBody": false,
    "hasQuery": false,
    "nonEnvelope": false
  },
  {
    "namespace": "payments",
    "command": "get-stripe-portal-return",
    "method": "getStripePortalReturn",
    "verb": "GET",
    "path": "/payments/stripe/portal/return",
    "pathParams": [],
    "params": [],
    "hasBody": false,
    "hasQuery": false,
    "nonEnvelope": false
  },
  {
    "namespace": "payments",
    "command": "list-auto-recharge-cards",
    "method": "listAutoRechargeCards",
    "verb": "GET",
    "path": "/payments/credits/auto-recharge/cards",
    "pathParams": [],
    "params": [],
    "hasBody": false,
    "hasQuery": false,
    "nonEnvelope": false
  },
  {
    "namespace": "payments",
    "command": "list-credit-transactions",
    "method": "listCreditTransactions",
    "verb": "GET",
    "path": "/payments/credits/transactions",
    "pathParams": [],
    "params": [
      {
        "name": "query",
        "role": "query"
      }
    ],
    "hasBody": false,
    "hasQuery": true,
    "nonEnvelope": false
  },
  {
    "namespace": "payments",
    "command": "purchase-stripe-plan",
    "method": "purchaseStripePlan",
    "verb": "POST",
    "path": "/payments/stripe/purchasePlan",
    "pathParams": [],
    "params": [
      {
        "name": "body",
        "role": "body"
      }
    ],
    "hasBody": true,
    "hasQuery": false,
    "nonEnvelope": false
  },
  {
    "namespace": "payments",
    "command": "update-auto-recharge",
    "method": "updateAutoRecharge",
    "verb": "PATCH",
    "path": "/payments/credits/auto-recharge",
    "pathParams": [],
    "params": [
      {
        "name": "body",
        "role": "body"
      }
    ],
    "hasBody": true,
    "hasQuery": false,
    "nonEnvelope": false
  },
  {
    "namespace": "payments",
    "command": "update-auto-recharge-card",
    "method": "updateAutoRechargeCard",
    "verb": "PATCH",
    "path": "/payments/credits/auto-recharge/cards/:paymentMethodId",
    "pathParams": [
      "paymentMethodId"
    ],
    "params": [
      {
        "name": "paymentMethodId",
        "role": "positional"
      },
      {
        "name": "body",
        "role": "body"
      }
    ],
    "hasBody": true,
    "hasQuery": false,
    "nonEnvelope": false
  },
  {
    "namespace": "redirect",
    "command": "resolve-redirect",
    "method": "resolveRedirect",
    "verb": "GET",
    "path": "/r/:code",
    "pathParams": [
      "code"
    ],
    "params": [
      {
        "name": "code",
        "role": "positional"
      }
    ],
    "hasBody": false,
    "hasQuery": false,
    "nonEnvelope": false
  },
  {
    "namespace": "referral",
    "command": "claim-referral",
    "method": "claimReferral",
    "verb": "POST",
    "path": "/referral/claim",
    "pathParams": [],
    "params": [
      {
        "name": "body",
        "role": "body"
      }
    ],
    "hasBody": true,
    "hasQuery": false,
    "nonEnvelope": false
  },
  {
    "namespace": "referral",
    "command": "get-referral-stats",
    "method": "getReferralStats",
    "verb": "GET",
    "path": "/referral/stats",
    "pathParams": [],
    "params": [],
    "hasBody": false,
    "hasQuery": false,
    "nonEnvelope": false
  },
  {
    "namespace": "rewards",
    "command": "claim-reward",
    "method": "claimReward",
    "verb": "POST",
    "path": "/rewards/claim",
    "pathParams": [],
    "params": [
      {
        "name": "body",
        "role": "body"
      }
    ],
    "hasBody": true,
    "hasQuery": false,
    "nonEnvelope": false
  },
  {
    "namespace": "rewards",
    "command": "get-my-rewards",
    "method": "getMyRewards",
    "verb": "GET",
    "path": "/rewards/me",
    "pathParams": [],
    "params": [],
    "hasBody": false,
    "hasQuery": false,
    "nonEnvelope": false
  },
  {
    "namespace": "rewards",
    "command": "unlink-discord",
    "method": "unlinkDiscord",
    "verb": "DELETE",
    "path": "/rewards/discord",
    "pathParams": [],
    "params": [],
    "hasBody": false,
    "hasQuery": false,
    "nonEnvelope": false
  },
  {
    "namespace": "teams",
    "command": "create-billing-portal",
    "method": "createBillingPortal",
    "verb": "POST",
    "path": "/teams/:teamId/billing/portal",
    "pathParams": [
      "teamId"
    ],
    "params": [
      {
        "name": "teamId",
        "role": "positional"
      },
      {
        "name": "body",
        "role": "body"
      }
    ],
    "hasBody": true,
    "hasQuery": false,
    "nonEnvelope": false
  },
  {
    "namespace": "teams",
    "command": "create-invite",
    "method": "createInvite",
    "verb": "POST",
    "path": "/teams/:teamId/invites",
    "pathParams": [
      "teamId"
    ],
    "params": [
      {
        "name": "teamId",
        "role": "positional"
      },
      {
        "name": "body",
        "role": "body"
      }
    ],
    "hasBody": true,
    "hasQuery": false,
    "nonEnvelope": false
  },
  {
    "namespace": "teams",
    "command": "get-billing-plan",
    "method": "getBillingPlan",
    "verb": "GET",
    "path": "/teams/:teamId/billing/plan",
    "pathParams": [
      "teamId"
    ],
    "params": [
      {
        "name": "teamId",
        "role": "positional"
      }
    ],
    "hasBody": false,
    "hasQuery": false,
    "nonEnvelope": false
  },
  {
    "namespace": "teams",
    "command": "get-my-usage",
    "method": "getMyUsage",
    "verb": "GET",
    "path": "/teams/me/usage",
    "pathParams": [],
    "params": [],
    "hasBody": false,
    "hasQuery": false,
    "nonEnvelope": false
  },
  {
    "namespace": "teams",
    "command": "get-team",
    "method": "getTeam",
    "verb": "GET",
    "path": "/teams/:teamId",
    "pathParams": [
      "teamId"
    ],
    "params": [
      {
        "name": "teamId",
        "role": "positional"
      }
    ],
    "hasBody": false,
    "hasQuery": false,
    "nonEnvelope": false
  },
  {
    "namespace": "teams",
    "command": "join-team",
    "method": "joinTeam",
    "verb": "POST",
    "path": "/teams/join",
    "pathParams": [],
    "params": [
      {
        "name": "body",
        "role": "body"
      }
    ],
    "hasBody": true,
    "hasQuery": false,
    "nonEnvelope": false
  },
  {
    "namespace": "teams",
    "command": "leave-team",
    "method": "leaveTeam",
    "verb": "POST",
    "path": "/teams/:teamId/leave",
    "pathParams": [
      "teamId"
    ],
    "params": [
      {
        "name": "teamId",
        "role": "positional"
      }
    ],
    "hasBody": false,
    "hasQuery": false,
    "nonEnvelope": false
  },
  {
    "namespace": "teams",
    "command": "list-invites",
    "method": "listInvites",
    "verb": "GET",
    "path": "/teams/:teamId/invites",
    "pathParams": [
      "teamId"
    ],
    "params": [
      {
        "name": "teamId",
        "role": "positional"
      }
    ],
    "hasBody": false,
    "hasQuery": false,
    "nonEnvelope": false
  },
  {
    "namespace": "teams",
    "command": "list-members",
    "method": "listMembers",
    "verb": "GET",
    "path": "/teams/:teamId/members",
    "pathParams": [
      "teamId"
    ],
    "params": [
      {
        "name": "teamId",
        "role": "positional"
      }
    ],
    "hasBody": false,
    "hasQuery": false,
    "nonEnvelope": false
  },
  {
    "namespace": "teams",
    "command": "list-teams",
    "method": "listTeams",
    "verb": "GET",
    "path": "/teams",
    "pathParams": [],
    "params": [],
    "hasBody": false,
    "hasQuery": false,
    "nonEnvelope": false
  },
  {
    "namespace": "teams",
    "command": "purchase-plan",
    "method": "purchasePlan",
    "verb": "POST",
    "path": "/teams/:teamId/billing/purchase",
    "pathParams": [
      "teamId"
    ],
    "params": [
      {
        "name": "teamId",
        "role": "positional"
      },
      {
        "name": "body",
        "role": "body"
      }
    ],
    "hasBody": true,
    "hasQuery": false,
    "nonEnvelope": false
  },
  {
    "namespace": "teams",
    "command": "revoke-invite",
    "method": "revokeInvite",
    "verb": "DELETE",
    "path": "/teams/:teamId/invites/:inviteId",
    "pathParams": [
      "teamId",
      "inviteId"
    ],
    "params": [
      {
        "name": "teamId",
        "role": "positional"
      },
      {
        "name": "inviteId",
        "role": "positional"
      }
    ],
    "hasBody": false,
    "hasQuery": false,
    "nonEnvelope": false
  },
  {
    "namespace": "teams",
    "command": "send-email-invite",
    "method": "sendEmailInvite",
    "verb": "POST",
    "path": "/teams/:teamId/invites/email",
    "pathParams": [
      "teamId"
    ],
    "params": [
      {
        "name": "teamId",
        "role": "positional"
      },
      {
        "name": "body",
        "role": "body"
      }
    ],
    "hasBody": true,
    "hasQuery": false,
    "nonEnvelope": false
  },
  {
    "namespace": "teams",
    "command": "switch-team",
    "method": "switchTeam",
    "verb": "POST",
    "path": "/teams/:teamId/switch",
    "pathParams": [
      "teamId"
    ],
    "params": [
      {
        "name": "teamId",
        "role": "positional"
      }
    ],
    "hasBody": false,
    "hasQuery": false,
    "nonEnvelope": false
  },
  {
    "namespace": "webhooks",
    "command": "create-core-webhook",
    "method": "createCoreWebhook",
    "verb": "POST",
    "path": "/webhooks/core",
    "pathParams": [],
    "params": [
      {
        "name": "body",
        "role": "body"
      }
    ],
    "hasBody": true,
    "hasQuery": false,
    "nonEnvelope": false
  },
  {
    "namespace": "webhooks",
    "command": "delete-core-webhook",
    "method": "deleteCoreWebhook",
    "verb": "DELETE",
    "path": "/webhooks/core/:id",
    "pathParams": [
      "id"
    ],
    "params": [
      {
        "name": "id",
        "role": "positional"
      }
    ],
    "hasBody": false,
    "hasQuery": false,
    "nonEnvelope": false
  },
  {
    "namespace": "webhooks",
    "command": "forward-webhook-ingress",
    "method": "forwardWebhookIngress",
    "verb": "POST",
    "path": "/webhooks/ingress/:uuid",
    "pathParams": [
      "uuid"
    ],
    "params": [
      {
        "name": "uuid",
        "role": "positional"
      },
      {
        "name": "body",
        "role": "body"
      }
    ],
    "hasBody": true,
    "hasQuery": false,
    "nonEnvelope": false
  },
  {
    "namespace": "webhooks",
    "command": "forward-webhook-ingress-with-path",
    "method": "forwardWebhookIngressWithPath",
    "verb": "POST",
    "path": "/webhooks/ingress/:uuid/:path",
    "pathParams": [
      "uuid",
      "path"
    ],
    "params": [
      {
        "name": "uuid",
        "role": "positional"
      },
      {
        "name": "path",
        "role": "positional"
      },
      {
        "name": "body",
        "role": "body"
      }
    ],
    "hasBody": true,
    "hasQuery": false,
    "nonEnvelope": false
  },
  {
    "namespace": "webhooks",
    "command": "get-core-webhook",
    "method": "getCoreWebhook",
    "verb": "GET",
    "path": "/webhooks/core/:id",
    "pathParams": [
      "id"
    ],
    "params": [
      {
        "name": "id",
        "role": "positional"
      }
    ],
    "hasBody": false,
    "hasQuery": false,
    "nonEnvelope": false
  },
  {
    "namespace": "webhooks",
    "command": "get-core-webhook-bandwidth",
    "method": "getCoreWebhookBandwidth",
    "verb": "GET",
    "path": "/webhooks/core/bandwidth",
    "pathParams": [],
    "params": [],
    "hasBody": false,
    "hasQuery": false,
    "nonEnvelope": false
  },
  {
    "namespace": "webhooks",
    "command": "list-core-webhooks",
    "method": "listCoreWebhooks",
    "verb": "GET",
    "path": "/webhooks/core",
    "pathParams": [],
    "params": [],
    "hasBody": false,
    "hasQuery": false,
    "nonEnvelope": false
  },
  {
    "namespace": "webhooks",
    "command": "receive-coinbase-payment-webhook",
    "method": "receiveCoinbasePaymentWebhook",
    "verb": "POST",
    "path": "/webhooks/payments/coinbase",
    "pathParams": [],
    "params": [
      {
        "name": "body",
        "role": "body"
      }
    ],
    "hasBody": true,
    "hasQuery": false,
    "nonEnvelope": false
  },
  {
    "namespace": "webhooks",
    "command": "receive-composio-webhook",
    "method": "receiveComposioWebhook",
    "verb": "POST",
    "path": "/webhooks/composio",
    "pathParams": [],
    "params": [
      {
        "name": "body",
        "role": "body"
      }
    ],
    "hasBody": true,
    "hasQuery": false,
    "nonEnvelope": false
  },
  {
    "namespace": "webhooks",
    "command": "receive-discord-webhook",
    "method": "receiveDiscordWebhook",
    "verb": "POST",
    "path": "/webhooks/discord",
    "pathParams": [],
    "params": [
      {
        "name": "body",
        "role": "body"
      }
    ],
    "hasBody": true,
    "hasQuery": false,
    "nonEnvelope": false
  },
  {
    "namespace": "webhooks",
    "command": "receive-github-webhook",
    "method": "receiveGithubWebhook",
    "verb": "POST",
    "path": "/webhooks/github",
    "pathParams": [],
    "params": [
      {
        "name": "body",
        "role": "body"
      }
    ],
    "hasBody": true,
    "hasQuery": false,
    "nonEnvelope": false
  },
  {
    "namespace": "webhooks",
    "command": "receive-managed-telegram-webhook",
    "method": "receiveManagedTelegramWebhook",
    "verb": "POST",
    "path": "/webhooks/telegram/managed/:param",
    "pathParams": [],
    "params": [
      {
        "name": "botId",
        "role": "positional"
      },
      {
        "name": "body",
        "role": "body"
      }
    ],
    "hasBody": true,
    "hasQuery": false,
    "nonEnvelope": false
  },
  {
    "namespace": "webhooks",
    "command": "receive-sentry-webhook",
    "method": "receiveSentryWebhook",
    "verb": "POST",
    "path": "/webhooks/sentry",
    "pathParams": [],
    "params": [
      {
        "name": "body",
        "role": "body"
      }
    ],
    "hasBody": true,
    "hasQuery": false,
    "nonEnvelope": false
  },
  {
    "namespace": "webhooks",
    "command": "receive-stripe-payment-webhook",
    "method": "receiveStripePaymentWebhook",
    "verb": "POST",
    "path": "/webhooks/payments/stripe",
    "pathParams": [],
    "params": [
      {
        "name": "body",
        "role": "body"
      }
    ],
    "hasBody": true,
    "hasQuery": false,
    "nonEnvelope": false
  },
  {
    "namespace": "webhooks",
    "command": "receive-telegram-webhook",
    "method": "receiveTelegramWebhook",
    "verb": "POST",
    "path": "/webhooks/telegram",
    "pathParams": [],
    "params": [
      {
        "name": "body",
        "role": "body"
      }
    ],
    "hasBody": true,
    "hasQuery": false,
    "nonEnvelope": false
  },
  {
    "namespace": "webhooks",
    "command": "update-core-webhook",
    "method": "updateCoreWebhook",
    "verb": "PATCH",
    "path": "/webhooks/core/:id",
    "pathParams": [
      "id"
    ],
    "params": [
      {
        "name": "id",
        "role": "positional"
      },
      {
        "name": "body",
        "role": "body"
      }
    ],
    "hasBody": true,
    "hasQuery": false,
    "nonEnvelope": false
  }
];
